import type { DungeonDefinition, DungeonId, MonsterDefinition, MonsterId } from './game';
import { demonTowerDungeon } from './level-data/demon-tower';
import { metroAbyssDungeon } from './level-data/metro-abyss';
import { starfallMineDungeon } from './level-data/starfall-mine';
import { rustHospitalDungeon } from './level-data/rust-hospital';
import { ashArenaDungeon } from './level-data/ash-arena';
import { dreamArchiveDungeon } from './level-data/dream-archive';
import { voidCitadelDungeon } from './level-data/void-citadel';
import { temporalObservatoryDungeon } from './level-data/temporal-observatory';
import { causalClearinghouseDungeon } from './level-data/causal-clearinghouse';
import { entropyArkDungeon } from './level-data/entropy-ark';
import { mirrorCycleCityDungeon } from './level-data/mirror-cycle-city';
import { redactionScriptoriumDungeon } from './level-data/redaction-scriptorium';
import { legacyAuctionCourtDungeon } from './level-data/legacy-auction-court';
import { genesisVaultDungeon } from './level-data/genesis-vault';
import { silentBroadcastTowerDungeon } from './level-data/silent-broadcast-tower';
import { lostShelterDungeon } from './level-data/lost-shelter';
import { falseTestimonyCourtDungeon } from './level-data/false-testimony-court';
import { combatReplayStageDungeon } from './level-data/combat-replay-stage';
import { panopticonCityDungeon } from './level-data/panopticon-city';

export const MONSTERS: Record<MonsterId, MonsterDefinition> = {
  fog_lesser_demon: {
    id: 'fog_lesser_demon',
    name: '雾中妖鬼',
    dungeonId: 'demon_tower_1',
    maxHp: 42,
    attack: 9,
    artPower: 0,
    defense: 2,
    speed: 9,
    rewardPoints: 160,
    drop: { demon_bone: 1 },
    ability: '第一回合试图撕裂玩家护甲。',
    counter: '雷火符或破甲剑能快速压低血线。'
  },
  tower_butcher: {
    id: 'tower_butcher',
    name: '剔骨塔卒',
    dungeonId: 'demon_tower_1',
    maxHp: 66,
    attack: 14,
    artPower: 0,
    defense: 6,
    speed: 6,
    rewardPoints: 230,
    drop: { demon_bone: 2 },
    ability: '生命高于一半时防御更高。',
    counter: '破甲剑抵消厚甲优势。'
  },
  tide_boatman: {
    id: 'tide_boatman',
    name: '潮影船夫',
    dungeonId: 'metro_abyss',
    maxHp: 54,
    attack: 12,
    artPower: 6,
    defense: 3,
    speed: 12,
    rewardPoints: 220,
    drop: { mirror_shell: 1 },
    ability: '影子会在玩家行动后补一击弱术法。',
    counter: '吐纳诀能削弱倒影干扰。'
  },
  mirror_thread_spider: {
    id: 'mirror_thread_spider',
    name: '镜丝织蛛',
    dungeonId: 'metro_abyss',
    maxHp: 72,
    attack: 15,
    artPower: 4,
    defense: 5,
    speed: 10,
    rewardPoints: 260,
    drop: { mirror_shell: 1, rift_dust: 1 },
    ability: '命中后降低玩家速度。',
    counter: '云隙步可以抵消迟缓。'
  },
  rail_wraith: {
    id: 'rail_wraith',
    name: '断轨怨影',
    dungeonId: 'metro_abyss',
    maxHp: 48,
    attack: 11,
    artPower: 10,
    defense: 2,
    speed: 13,
    rewardPoints: 210,
    drop: { rift_dust: 1 },
    ability: '传送节点附近会闪避一次重击。',
    counter: '小界门符能锚定它的位置。'
  },
  mine_shell_guard: {
    id: 'mine_shell_guard',
    name: '矿壳守卫',
    dungeonId: 'starfall_mine',
    maxHp: 74,
    attack: 16,
    artPower: 0,
    defense: 8,
    speed: 5,
    rewardPoints: 310,
    drop: { star_iron: 1 },
    ability: '高防御，普通短刃很难打穿。',
    counter: '破甲剑是最稳定答案。'
  },
  spark_imp: {
    id: 'spark_imp',
    name: '跳火小鬼',
    dungeonId: 'starfall_mine',
    maxHp: 36,
    attack: 9,
    artPower: 8,
    defense: 2,
    speed: 15,
    rewardPoints: 180,
    drop: { medicine_ash: 1 },
    ability: '第三回合爆出火星追加伤害。',
    counter: '防御动作能吃掉爆发回合。'
  },
  portal_molt_beast: {
    id: 'portal_molt_beast',
    name: '裂门蜕兽',
    dungeonId: 'starfall_mine',
    maxHp: 86,
    attack: 17,
    artPower: 8,
    defense: 6,
    speed: 9,
    rewardPoints: 360,
    drop: { cracked_core: 1, rift_dust: 1 },
    ability: '每两回合偏移一次，降低下一次非符咒伤害。',
    counter: '雷火符和观门法能锁住裂隙。'
  },
  plague_orderly: {
    id: 'plague_orderly',
    name: '锈疫护工',
    dungeonId: 'rust_hospital',
    maxHp: 80,
    attack: 16,
    artPower: 8,
    defense: 6,
    speed: 11,
    rewardPoints: 320,
    drop: { medicine_ash: 1, rift_dust: 1 },
    ability: '攻击会附带锈疫余波，拖长战斗会更危险。',
    counter: '定神香和铁衣诀能降低锈疫压制。'
  },
  pulse_doctor: {
    id: 'pulse_doctor',
    name: '脉冲医师',
    dungeonId: 'rust_hospital',
    maxHp: 100,
    attack: 15,
    artPower: 18,
    defense: 7,
    speed: 12,
    rewardPoints: 400,
    drop: { method_page: 1 },
    ability: '每三回合释放一次群体脉冲。',
    counter: '虚界灯和高灵力能压住脉冲。'
  },
  ash_duelist: {
    id: 'ash_duelist',
    name: '灰烬斗士',
    dungeonId: 'ash_arena',
    maxHp: 92,
    attack: 20,
    artPower: 0,
    defense: 8,
    speed: 13,
    rewardPoints: 380,
    drop: { star_iron: 1 },
    ability: '低血量时攻击提高。',
    counter: '高防护甲或云隙步能避免被终结。'
  },
  furnace_judge: {
    id: 'furnace_judge',
    name: '炉心裁判',
    dungeonId: 'ash_arena',
    maxHp: 112,
    attack: 20,
    artPower: 15,
    defense: 9,
    speed: 9,
    rewardPoints: 460,
    drop: { cracked_core: 1 },
    ability: '会判定玩家上一回合动作并追加惩罚。',
    counter: '防御和术法交替能降低裁决收益。'
  },
  paper_librarian: {
    id: 'paper_librarian',
    name: '纸面馆主',
    dungeonId: 'dream_archive',
    maxHp: 98,
    attack: 14,
    artPower: 20,
    defense: 5,
    speed: 15,
    rewardPoints: 430,
    drop: { method_page: 1, hidden_stone: 1 },
    ability: '把玩家的上一条日志折成幻觉陷阱。',
    counter: '吐纳诀和虚心诀能维持自我。'
  },
  dream_jailer: {
    id: 'dream_jailer',
    name: '梦牢看守',
    dungeonId: 'dream_archive',
    maxHp: 126,
    attack: 20,
    artPower: 20,
    defense: 9,
    speed: 10,
    rewardPoints: 520,
    drop: { cracked_core: 1, method_page: 1 },
    ability: '会锁住一个道具位，逼玩家用基础能力过关。',
    counter: '宠物和成长属性能绕开道具封锁。'
  },
  void_knight: {
    id: 'void_knight',
    name: '虚界骑士',
    dungeonId: 'void_citadel',
    maxHp: 128,
    attack: 22,
    artPower: 12,
    defense: 11,
    speed: 12,
    rewardPoints: 540,
    drop: { cracked_core: 1, rift_dust: 1 },
    ability: '第一次受到致命伤害时保留 1 点生命。',
    counter: '淬星剑胚和虚心诀能稳定终结。'
  },
  main_god_echo: {
    id: 'main_god_echo',
    name: '主神残响',
    dungeonId: 'void_citadel',
    maxHp: 152,
    attack: 22,
    artPower: 26,
    defense: 11,
    speed: 15,
    rewardPoints: 660,
    drop: { cracked_core: 2, method_page: 1 },
    ability: '复制玩家最高的一项派生属性。',
    counter: '均衡成长比单点堆数值更稳定。'
  },
  clockwork_scout: {
    id: 'clockwork_scout',
    name: '发条侦察兵',
    dungeonId: 'temporal_observatory',
    maxHp: 142,
    attack: 23,
    artPower: 18,
    defense: 10,
    speed: 18,
    rewardPoints: 590,
    drop: { chronal_glass: 1, rift_dust: 1 },
    ability: '每隔一回合提前执行下一次攻击，持续拖延会失去行动窗口。',
    counter: '云隙步与稳定爆发能打断它的加速循环。'
  },
  epoch_sentinel: {
    id: 'epoch_sentinel',
    name: '纪元哨卫',
    dungeonId: 'temporal_observatory',
    maxHp: 168,
    attack: 25,
    artPower: 24,
    defense: 13,
    speed: 14,
    rewardPoints: 700,
    drop: { chronal_glass: 2, cracked_core: 1 },
    ability: '记录上一回合承受的最高伤害，并在下次行动时复制其时间残响。',
    counter: '交替使用武力、术法与防御可以压低残响峰值。'
  },
  zero_hour_regent: {
    id: 'zero_hour_regent',
    name: '零时摄政',
    dungeonId: 'temporal_observatory',
    maxHp: 208,
    attack: 28,
    artPower: 32,
    defense: 15,
    speed: 17,
    rewardPoints: 860,
    drop: { chronal_glass: 3, method_page: 1 },
    ability: '在过去复演与未来预判之间切换，连续使用同类动作会被它提前反制。',
    counter: '均衡轮换行动并完成双锚校准，能限制它改写零点。'
  },
  verdict_usher: {
    id: 'verdict_usher',
    name: '裁决执事',
    dungeonId: 'causal_clearinghouse',
    maxHp: 162,
    attack: 26,
    artPower: 22,
    defense: 12,
    speed: 20,
    rewardPoints: 660,
    drop: { causal_seal: 1 },
    ability: '把连续使用的同类动作登记为惯例，并据此追加一次针对性裁决。',
    counter: '交替武力、术法与防御，可以让它无法形成稳定判例。'
  },
  paradox_bailiff: {
    id: 'paradox_bailiff',
    name: '悖论法警',
    dungeonId: 'causal_clearinghouse',
    maxHp: 196,
    attack: 29,
    artPower: 29,
    defense: 16,
    speed: 18,
    rewardPoints: 820,
    drop: { causal_seal: 2 },
    ability: '先宣判结果再追认原因，上一回合的最高伤害会被它改写成反证。',
    counter: '压低单次伤害峰值并及时切换行动类型，能拆散它的悖论证词。'
  },
  zero_sum_auditor: {
    id: 'zero_sum_auditor',
    name: '零和审计官',
    dungeonId: 'causal_clearinghouse',
    maxHp: 242,
    attack: 32,
    artPower: 38,
    defense: 17,
    speed: 19,
    rewardPoints: 1030,
    drop: { causal_seal: 3, method_page: 1 },
    ability: '在因端收益与果端代价之间强制轧差，重复获利会被折算成终审伤害。',
    counter: '完成双侧证词核验并均衡轮换行动，能阻止它把战斗写成零和账本。'
  },
  entropy_deckhand: {
    id: 'entropy_deckhand',
    name: '熵舱水手',
    dungeonId: 'entropy_ark',
    maxHp: 212,
    attack: 31,
    artPower: 22,
    defense: 15,
    speed: 22,
    rewardPoints: 760,
    drop: { entropy_crystal: 1 },
    ability: '首次清理后扰乱附近航迹，让方舟的自动升熵压力提前显现。',
    counter: '稳定轮换行动并及时降熵，可以避免被连续失序浪涌压制。'
  },
  dissipation_navigator: {
    id: 'dissipation_navigator',
    name: '耗散领航员',
    dungeonId: 'entropy_ark',
    maxHp: 258,
    attack: 34,
    artPower: 34,
    defense: 18,
    speed: 20,
    rewardPoints: 940,
    drop: { entropy_crystal: 2 },
    ability: '把连续推进积累成耗散航差，并在下一次术法中释放全部失序读数。',
    counter: '交替稳航与爆发、压低单次航差，可以拆散它的耗散结算。'
  },
  last_helmsman: {
    id: 'last_helmsman',
    name: '终末舵手',
    dungeonId: 'entropy_ark',
    maxHp: 318,
    attack: 38,
    artPower: 44,
    defense: 20,
    speed: 22,
    rewardPoints: 1240,
    drop: { entropy_crystal: 3, method_page: 1 },
    ability: '把方舟崩解层叠入终末舵轮，半血后以热寂航向放大每一次失序。',
    counter: '先完成压载锚与航迹刻印，再以降熵手段限制它的崩解层。'
  },
  parallax_hunter: {
    id: 'parallax_hunter',
    name: '视差猎手',
    dungeonId: 'mirror_cycle_city',
    maxHp: 236,
    attack: 34,
    artPower: 27,
    defense: 17,
    speed: 24,
    rewardPoints: 840,
    drop: { phase_glass: 1 },
    ability: '同时锁定现实本体与镜像落点，连续使用同类行动会让两条猎杀线迅速重合。',
    counter: '交替武力与术法并主动换相，可以持续拉开本体和倒影的视差。'
  },
  mirror_chorus: {
    id: 'mirror_chorus',
    name: '镜群合唱者',
    dungeonId: 'mirror_cycle_city',
    maxHp: 286,
    attack: 37,
    artPower: 39,
    defense: 20,
    speed: 23,
    rewardPoints: 1040,
    drop: { phase_glass: 2 },
    ability: '把上一回合的主导伤害唱成多重回声，并在当前相位中放大对应反制。',
    counter: '利用相位偏向轮换输出类型，可以让合唱无法维持同一段反制声部。'
  },
  nameless_reflection: {
    id: 'nameless_reflection',
    name: '无名镜王',
    dungeonId: 'mirror_cycle_city',
    maxHp: 356,
    attack: 42,
    artPower: 50,
    defense: 23,
    speed: 25,
    rewardPoints: 1380,
    drop: { phase_glass: 3, method_page: 1 },
    ability: '以未锚定相位生成镜壳，觉醒后仍保留尚未击碎的外壳并持续改写伤害归属。',
    counter: '完成相位选择并尽量校准双锚，用不同的正伤害行动逐层击碎镜壳。'
  },
  erasure_copyist: {
    id: 'erasure_copyist',
    name: '删界抄写员',
    dungeonId: 'redaction_scriptorium',
    maxHp: 262,
    attack: 39,
    artPower: 32,
    defense: 19,
    speed: 26,
    rewardPoints: 920,
    drop: { redaction_ink: 1 },
    ability: '记录连续使用的同类基础攻势，重复落笔时削弱伤害并沿原动作施加删改反噬。',
    counter: '在武力与术法之间交替出手，守势与道具也能打断重复句式。'
  },
  palimpsest_censor: {
    id: 'palimpsest_censor',
    name: '覆页裁定者',
    dungeonId: 'redaction_scriptorium',
    maxHp: 318,
    attack: 42,
    artPower: 45,
    defense: 22,
    speed: 25,
    rewardPoints: 1150,
    drop: { redaction_ink: 2 },
    ability: '奇数页审查武力、偶数页审查术法，命中当前覆页禁则的伤害会被改写为旁注。',
    counter: '奇数回合使用术法、偶数回合使用武力，或以守势观察下一页裁定。'
  },
  last_redactor: {
    id: 'last_redactor',
    name: '终稿删界官',
    dungeonId: 'redaction_scriptorium',
    maxHp: 398,
    attack: 47,
    artPower: 56,
    defense: 26,
    speed: 28,
    rewardPoints: 1510,
    drop: { redaction_ink: 3, method_page: 1 },
    ability: '把条款裁定与终稿权限叠入删界笔，每一次未经认证的改动都会强化最终删除。',
    counter: '先结算沿途条款并保留足够生命，再以认证版本持续压住终稿权限。'
  },
  reserve_bailiff: {
    id: 'reserve_bailiff',
    name: '底价执役',
    dungeonId: 'legacy_auction_court',
    maxHp: 292,
    attack: 45,
    artPower: 38,
    defense: 22,
    speed: 29,
    rewardPoints: 1080,
    drop: { legacy_scrip: 1 },
    ability: '把第一段正伤害登记为保留价，后续更低伤害会被折半并触发确定反拍。',
    counter: '先防御可清空保留价，再用低伤害重新起拍并逐步抬高输出。'
  },
  inheritance_mimic: {
    id: 'inheritance_mimic',
    name: '遗产拟形体',
    dungeonId: 'legacy_auction_court',
    maxHp: 350,
    attack: 47,
    artPower: 50,
    defense: 24,
    speed: 28,
    rewardPoints: 1290,
    drop: { legacy_scrip: 2 },
    ability: '止血丹或雷火符会令它生成单次溯源盾，使下一次直接正伤害减半。',
    counter: '避免战斗道具，或先用低伤害攻击剥掉溯源盾再投入主力攻势。'
  },
  estate_auctioneer: {
    id: 'estate_auctioneer',
    name: '遗产执槌人',
    dungeonId: 'legacy_auction_court',
    maxHp: 456,
    attack: 53,
    artPower: 64,
    defense: 30,
    speed: 31,
    rewardPoints: 1720,
    drop: { legacy_scrip: 3, method_page: 1 },
    ability: '冻结四类拍品的竞标结果，并在觉醒后放大未妥善清算的遗产条款。',
    counter: '入场装备快照与沿途竞标共同决定终场修正，先清算拍品再挑战执槌人。'
  },
  gene_stalker: {
    id: 'gene_stalker',
    name: '基因猎犬',
    dungeonId: 'genesis_vault',
    maxHp: 390,
    attack: 51,
    artPower: 48,
    defense: 26,
    speed: 34,
    rewardPoints: 1420,
    drop: { genesis_serum: 1 },
    ability: '记录上一回合的直接攻势；连续重复武力或术法时会适应伤害并发动额外追猎撕咬。',
    counter: '交替武力与术法，或以防御和道具打断连续表达，能让追猎适应失去目标。'
  },
  mutation_guardian: {
    id: 'mutation_guardian',
    name: '变异守库体',
    dungeonId: 'genesis_vault',
    maxHp: 435,
    attack: 56,
    artPower: 54,
    defense: 30,
    speed: 30,
    rewardPoints: 1560,
    drop: { genesis_serum: 2 },
    ability: '奇数回合展开武力甲壳、偶数回合展开术法甲壳，命中对应类型时会大幅适应伤害。',
    counter: '奇数回合施展术法、偶数回合使用武力，按甲壳节律切换输出即可绕过适应。'
  },
  primal_curator: {
    id: 'primal_curator',
    name: '原型典藏官',
    dungeonId: 'genesis_vault',
    maxHp: 525,
    attack: 60,
    artPower: 72,
    defense: 34,
    speed: 34,
    rewardPoints: 1980,
    drop: { genesis_serum: 3, method_page: 1 },
    ability: '读取本局冻结的基因拼接与血统原型，在觉醒后把原型库法则转化为终场攻防修正。',
    counter: '先完成三座拼接台并保留血清余量，再依照当前法则修正选择稳定的输出与恢复窗口。'
  },
  frequency_leech: {
    id: 'frequency_leech',
    name: '频段寄生体',
    dungeonId: 'silent_broadcast_tower',
    maxHp: 430,
    attack: 58,
    artPower: 62,
    defense: 30,
    speed: 37,
    rewardPoints: 1690,
    drop: { silence_core: 1 },
    ability: '锁定上一回合的直接攻击频段；连续使用武力或术法时会吸收同频伤害，并追加一次灵力啃噬。',
    counter: '交替武力、术法与防御，或用战斗道具切断连续频段，能阻止寄生体完成同频附着。'
  },
  dead_air_mimic: {
    id: 'dead_air_mimic',
    name: '死频拟声体',
    dungeonId: 'silent_broadcast_tower',
    maxHp: 455,
    attack: 61,
    artPower: 68,
    defense: 31,
    speed: 34,
    rewardPoints: 1780,
    drop: { silence_core: 1, rift_dust: 1 },
    ability: '录下本回合受到的最高直接伤害，并在下一次行动时以延迟拟声回放同类冲击。',
    counter: '压低单次伤害峰值并轮换攻击类型，防御回合还能让拟声体的下一段录音失去有效样本。'
  },
  broadcast_warden: {
    id: 'broadcast_warden',
    name: '广播守卫',
    dungeonId: 'silent_broadcast_tower',
    maxHp: 500,
    attack: 65,
    artPower: 70,
    defense: 36,
    speed: 32,
    rewardPoints: 1910,
    drop: { silence_core: 2 },
    ability: '奇数回合封锁武力频带、偶数回合封锁术法频带，命中被封锁频带时会生成静默护盾并反击。',
    counter: '奇数回合施展术法、偶数回合使用武力，按广播灯号反向轮换即可绕开频带封锁。'
  },
  last_broadcaster: {
    id: 'last_broadcaster',
    name: '末频道播音主',
    dungeonId: 'silent_broadcast_tower',
    maxHp: 585,
    attack: 70,
    artPower: 84,
    defense: 40,
    speed: 36,
    rewardPoints: 2280,
    drop: { silence_core: 3, method_page: 1 },
    ability: '把三座中继台与空白频道叠成终场广播，觉醒后会放大尚未切断的频段，并将重复行动写入永久播音。',
    counter: '先重启北段、中央与南段中继台，再轮换武力、术法和守势，利用停播窗口集中终结主频道。'
  },
  mimic_survivor: {
    id: 'mimic_survivor',
    name: '拟声幸存者',
    dungeonId: 'lost_shelter',
    maxHp: 480,
    attack: 64,
    artPower: 72,
    defense: 33,
    speed: 38,
    rewardPoints: 1870,
    drop: { rescue_badge: 1 },
    ability: '复制队伍中最虚弱者的声音与上一回合动作；连续回应同类求救时，它会借机重演该动作并扰乱分诊。',
    counter: '先观察呼吸与名单编号，再交替武力、术法和防御；不要连续回应相同求救口令，即可让伪装失去同步样本。'
  },
  shelter_enforcer: {
    id: 'shelter_enforcer',
    name: '避难所执行体',
    dungeonId: 'lost_shelter',
    maxHp: 510,
    attack: 68,
    artPower: 74,
    defense: 38,
    speed: 34,
    rewardPoints: 2000,
    drop: { rescue_badge: 2 },
    ability: '奇数回合封锁推进路线、偶数回合标记治疗目标；命中当前封锁行为会使它获得护送权限盾并立即反击。',
    counter: '奇数回合优先治疗或防御、偶数回合集中推进输出，按检查灯号反向行动即可绕过权限盾并保住幸存者。'
  },
  evacuation_horror: {
    id: 'evacuation_horror',
    name: '撤离畸变体',
    dungeonId: 'lost_shelter',
    maxHp: 555,
    attack: 72,
    artPower: 78,
    defense: 40,
    speed: 35,
    rewardPoints: 2150,
    drop: { rescue_badge: 2, rift_dust: 1 },
    ability: '记录最近一次检查点选择，并把连续治疗压成群体抽取、把连续强推压成高速冲撞，在下一回合释放。',
    counter: '让治疗与推进至少各出现一次，并在畸变体蓄力时切换行动类型；均衡护送节奏能够拆散它的撤离重演。'
  },
  shelter_overseer: {
    id: 'shelter_overseer',
    name: '失联总控',
    dungeonId: 'lost_shelter',
    maxHp: 650,
    attack: 76,
    artPower: 90,
    defense: 44,
    speed: 38,
    rewardPoints: 2480,
    drop: { rescue_badge: 3, method_page: 1 },
    ability: '冻结首领战开始时的幸存者生命快照，把三处检查点的护送选择写入接管协议，并在觉醒后放大单一选择的代价。',
    counter: '先完成三处检查点，至少治疗与强推各一次并让幸存者保持半数以上生命；首领觉醒后继续轮换攻防，在接管间隙集中终结。'
  },
  hostile_witness: {
    id: 'hostile_witness',
    name: '敌意证人',
    dungeonId: 'false_testimony_court',
    maxHp: 520,
    attack: 72,
    artPower: 82,
    defense: 38,
    speed: 40,
    rewardPoints: 2080,
    drop: { truth_fragment: 1 },
    ability: '记录上一回合受到的直接质询；连续使用武力或术法时，它会把重复攻势改写成矛盾口供并立即反诘。',
    counter: '交替武力、术法与防御，或用战斗道具打断连续质询；不让同一种回答连续出现，就能使伪造口供失去参照。'
  },
  archive_censor: {
    id: 'archive_censor',
    name: '档案删录官',
    dungeonId: 'false_testimony_court',
    maxHp: 550,
    attack: 76,
    artPower: 88,
    defense: 41,
    speed: 35,
    rewardPoints: 2200,
    drop: { truth_fragment: 2 },
    ability: '奇数回合删录武力证据、偶数回合删录术法证据；命中被删类型会替它生成一层无记录护盾并追加批注伤害。',
    counter: '奇数回合使用术法、偶数回合使用武力，并在护盾出现时先防御观察；按删录灯号反向行动即可保住完整证据链。'
  },
  perjury_hound: {
    id: 'perjury_hound',
    name: '伪证猎犬',
    dungeonId: 'false_testimony_court',
    maxHp: 590,
    attack: 80,
    artPower: 92,
    defense: 43,
    speed: 38,
    rewardPoints: 2340,
    drop: { truth_fragment: 2, rift_dust: 1 },
    ability: '嗅取最近两回合的行动顺序，若两次回答同类或连续使用道具，便会锁定矛盾并发动高速追咬。',
    counter: '让武力、术法、防御和道具保持轮换，在猎犬伏低蓄势时切换行动类型，即可让它追向一条不存在的伪证气味。'
  },
  false_testimony_judge: {
    id: 'false_testimony_judge',
    name: '伪证主审',
    dungeonId: 'false_testimony_court',
    maxHp: 700,
    attack: 84,
    artPower: 100,
    defense: 48,
    speed: 40,
    rewardPoints: 2690,
    drop: { truth_fragment: 3, method_page: 1 },
    ability: '冻结首领战开始时的三证裁定快照，把未揭示、未净证与错误指控写入终审判词；觉醒后还会放大已经翻案的缺口。',
    counter: '先揭示三份证据、至少净证两份并完成正确指控，保留未翻案状态进入首领战；觉醒后轮换攻防，在判词换页时集中终结。'
  },
  cue_stalker: {
    id: 'cue_stalker',
    name: '场记潜猎者',
    dungeonId: 'combat_replay_stage',
    maxHp: 560,
    attack: 80,
    artPower: 92,
    defense: 42,
    speed: 42,
    rewardPoints: 2280,
    drop: { combat_reel: 1 },
    ability: '记录上一回合的直接攻势；连续重复武力或术法时，它会沿开场提示扑入镜头并追加追猎。',
    counter: '交替武力、术法与防御，或用战斗道具打断连续表达，让场记板无法预测下一次动作。'
  },
  continuity_editor: {
    id: 'continuity_editor',
    name: '连续性剪辑师',
    dungeonId: 'combat_replay_stage',
    maxHp: 590,
    attack: 84,
    artPower: 98,
    defense: 45,
    speed: 37,
    rewardPoints: 2400,
    drop: { combat_reel: 2 },
    ability: '奇数回合删改武力镜头、偶数回合删改术法镜头；命中被删类型会生成连续性护盾并反击。',
    counter: '奇数回合使用术法、偶数回合使用武力，按场记灯号反向轮换即可保住动作连续性。'
  },
  retake_double: {
    id: 'retake_double',
    name: '重拍替身',
    dungeonId: 'combat_replay_stage',
    maxHp: 630,
    attack: 88,
    artPower: 102,
    defense: 47,
    speed: 40,
    rewardPoints: 2540,
    drop: { combat_reel: 2, rift_dust: 1 },
    ability: '复刻最近两回合的动作顺序，若两次表达同类或连续使用道具，便会把废弃镜头重拍成高速反击。',
    counter: '让武力、术法、防御和道具保持轮换，在替身对焦时切换动作类型，使重拍版本失去原始样本。'
  },
  final_cut_director: {
    id: 'final_cut_director',
    name: '终剪导演',
    dungeonId: 'combat_replay_stage',
    maxHp: 750,
    attack: 92,
    artPower: 110,
    defense: 52,
    speed: 42,
    rewardPoints: 2900,
    drop: { combat_reel: 3, method_page: 1 },
    ability: '冻结首领战开始时的三段录制与路线快照，把缺失镜头、未完成路线和重拍痕迹写入终剪版本。',
    counter: '先完成甲乙丙三段录制并锁定路线，再轮换攻防，在终剪换卷时集中终结。'
  },
  sweep_sentinel: {
    id: 'sweep_sentinel',
    name: '扫视哨兵',
    dungeonId: 'panopticon_city',
    maxHp: 600,
    attack: 90,
    artPower: 106,
    defense: 50,
    speed: 42,
    rewardPoints: 2660,
    drop: { observation_shard: 1 },
    ability: '按当前扫描相位展开扇形视锥，连续停留在同类行动上会被标记并追加一次术法扫射。',
    counter: '保持武力、术法与防御轮换，并利用移动后的相位变化让下一次视锥落在空街。'
  },
  blindspot_auditor: {
    id: 'blindspot_auditor',
    name: '盲区审计官',
    dungeonId: 'panopticon_city',
    maxHp: 640,
    attack: 94,
    artPower: 110,
    defense: 52,
    speed: 42,
    rewardPoints: 2780,
    drop: { observation_shard: 2 },
    ability: '核对最近两次行动中的空白记录，若连续表达同类意图便把盲区登记成违法路径并反击。',
    counter: '用不同类型的直接行动填满审计窗口，在它翻页核验时集中打穿防线。'
  },
  exposure_double: {
    id: 'exposure_double',
    name: '曝光替身',
    dungeonId: 'panopticon_city',
    maxHp: 680,
    attack: 97,
    artPower: 115,
    defense: 54,
    speed: 43,
    rewardPoints: 2920,
    drop: { observation_shard: 2, phase_glass: 1 },
    ability: '复制最近一次被扫描记录的动作，并在探索者重复该动作时用同一轮廓发动高速反击。',
    counter: '观察替身当前复制的表达，主动切换武力、术法或守御，让复制轮廓失去原始样本。'
  },
  all_sight_warden: {
    id: 'all_sight_warden',
    name: '万目监察者',
    dungeonId: 'panopticon_city',
    maxHp: 810,
    attack: 100,
    artPower: 120,
    defense: 56,
    speed: 44,
    rewardPoints: 3300,
    drop: { observation_shard: 3, method_page: 1 },
    ability: '冻结首领战开始时的路线、曝光与折光快照，把每一次被看见的移动转写为监察火力。',
    counter: '先完成三座盲区中继并锁定路线，利用入场冻结装备修正快照，再轮换攻防终结万目核心。'
  }
};

export const DUNGEON_ORDER: DungeonId[] = [
  'demon_tower_1',
  'metro_abyss',
  'starfall_mine',
  'rust_hospital',
  'ash_arena',
  'dream_archive',
  'void_citadel',
  'temporal_observatory',
  'causal_clearinghouse',
  'entropy_ark',
  'mirror_cycle_city',
  'redaction_scriptorium',
  'legacy_auction_court',
  'genesis_vault',
  'silent_broadcast_tower',
  'lost_shelter',
  'false_testimony_court',
  'combat_replay_stage',
  'panopticon_city'
];

export const DUNGEONS: Record<DungeonId, DungeonDefinition> = {
  demon_tower_1: demonTowerDungeon,
  metro_abyss: metroAbyssDungeon,
  starfall_mine: starfallMineDungeon,
  rust_hospital: rustHospitalDungeon,
  ash_arena: ashArenaDungeon,
  dream_archive: dreamArchiveDungeon,
  void_citadel: voidCitadelDungeon,
  temporal_observatory: temporalObservatoryDungeon,
  causal_clearinghouse: causalClearinghouseDungeon,
  entropy_ark: entropyArkDungeon,
  mirror_cycle_city: mirrorCycleCityDungeon,
  redaction_scriptorium: redactionScriptoriumDungeon,
  legacy_auction_court: legacyAuctionCourtDungeon,
  genesis_vault: genesisVaultDungeon,
  silent_broadcast_tower: silentBroadcastTowerDungeon,
  lost_shelter: lostShelterDungeon,
  false_testimony_court: falseTestimonyCourtDungeon,
  combat_replay_stage: combatReplayStageDungeon,
  panopticon_city: panopticonCityDungeon
};
